# Generated by Django 2.2.10 on 2020-02-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerFName', models.CharField(max_length=50)),
                ('CustomerLName', models.CharField(max_length=50)),
                ('SSN', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
