# Generated by Django 2.2.10 on 2020-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='UserName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
