# Generated by Django 3.0.4 on 2020-03-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_photographer_style'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fav_photographers',
            field=models.ManyToManyField(related_name='fav_photographers', to='photographers.Photographer'),
        ),
    ]
