# Generated by Django 2.2.10 on 2020-02-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerinfo_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='UserName',
            new_name='Username',
        ),
    ]
