# Generated by Django 3.0.4 on 2020-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_photographer_style'),
        ('customers', '0003_auto_20200312_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fav_photographers',
            field=models.ManyToManyField(null=True, related_name='fav_photographers', to='photographers.Photographer'),
        ),
    ]
