# Generated by Django 2.2.10 on 2020-02-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200210_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='PaymentInfo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
