# Generated by Django 3.0.4 on 2020-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_photographer_style'),
        ('customers', '0004_auto_20200312_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fav_photographers',
            field=models.ManyToManyField(blank=True, null=True, related_name='fav_photographers', to='photographers.Photographer'),
        ),
    ]
