# Generated by Django 2.2.10 on 2020-03-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('customers', '0001_initial'),
        ('photographers', '0002_photographer_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('REMAINING', 'Remaining')], max_length=10)),
                ('payment_amount', models.FloatField()),
                ('payment_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_customer', to='customers.Customer')),
                ('payment_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_for_job', to='jobs.JobInfo')),
                ('payment_photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_photographer', to='photographers.Photographer')),
            ],
        ),
    ]
