# Generated by Django 3.0.4 on 2020-03-26 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewinfo',
            old_name='ReviewJob',
            new_name='reviewJob',
        ),
        migrations.RemoveField(
            model_name='reviewinfo',
            name='ReviewDetail',
        ),
        migrations.AddField(
            model_name='reviewinfo',
            name='rateJob',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewinfo',
            name='reviewDetail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
