# Generated by Django 2.2.10 on 2020-03-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('photographers', '0002_photographer_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoshoot_date', models.DateField()),
                ('photoshoot_time', models.CharField(choices=[('HALF_DAY_MORNING', 'Half-day(Morning-Noon)'), ('HALF_DAY_NOON', 'Half-day(Noon-Evening)'), ('FULL_DAY', 'Full-Day'), ('NIGHT', 'Night'), ('FULL_DAY_NIGHT', 'Full-Day and Night')], max_length=20)),
                ('job_avail_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_avail_time', to='photographers.AvailTime')),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=250)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_status', models.CharField(choices=[('PENDING', 'Pending'), ('DECLINED', 'Declined'), ('MATCHED', 'Matched'), ('PAID', 'Paid'), ('CANCELLED_BY_PHOTOGRAPHER', 'Cancelled by photographer'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by customer'), ('PROCESSING', 'Processing Photos'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='PENDING', max_length=25)),
                ('job_style', models.CharField(choices=[('GRADUATION', 'Graduation'), ('LANDSCAPE', 'Landscape'), ('PORTRAIT', 'Portrait'), ('PRODUCT', 'Product'), ('FASHION', 'Fashion'), ('EVENT', 'Event'), ('WEDDING', 'Wedding'), ('NONE', 'None')], max_length=15)),
                ('job_location', models.CharField(max_length=400)),
                ('job_expected_complete_date', models.DateField()),
                ('job_special_requirement', models.CharField(blank=True, max_length=400, null=True)),
                ('job_url', models.URLField(blank=True, null=True)),
                ('job_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_customer', to='customers.Customer')),
                ('job_photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_of_photographer', to='photographers.Photographer')),
                ('job_reservation', models.ManyToManyField(null=True, to='jobs.JobReservation')),
            ],
        ),
    ]
