# Generated by Django 3.0.3 on 2020-02-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('JobID', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('JobStatus', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('DECLINED', 'Declined'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('PROCESSING', 'Processing Photos'), ('DONE', 'DONE'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], max_length=10)),
                ('JobStartDate', models.DateField()),
                ('JobEndDate', models.DateField()),
                ('JobCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_by_customer', to='customers.Customer')),
            ],
        ),
    ]
