# Generated by Django 3.0.3 on 2020-03-10 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('jobs', '0001_initial'),
        ('photographers', '0002_auto_20200310_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='JobCustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_by_customer', to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='JobPhotographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_of_photographer', to='photographers.Photographer'),
        ),
    ]
