# Generated by Django 3.0.3 on 2020-03-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreservation',
            name='job_reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_avail_time', to='photographers.AvailTime'),
        ),
    ]
