# Generated by Django 3.0.3 on 2020-02-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerinfo_paymentinfo'),
        ('jobs', '0002_jobinfo_jobstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='JobEndDate',
            field=models.DateField(default='1999-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='JobID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='JobStartDate',
            field=models.DateField(default='1998-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='JobCustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerJob', to='customers.CustomerInfo'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='JobStatus',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('PROCESSING', 'Processing Photos'), ('COMPLETED', 'Completed')], max_length=10),
        ),
    ]
