# Generated by Django 3.0.4 on 2020-03-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200314_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='job_title',
            field=models.CharField(default='No title', max_length=250),
            preserve_default=False,
        ),
    ]
