# Generated by Django 3.0.3 on 2020-02-19 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0004_auto_20200219_0623'),
        ('jobs', '0002_auto_20200219_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='JobPhotographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_of_photographer', to='photographers.Photographer'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='JobStatus',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('DECLINED', 'Declined'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('PROCESSING', 'Processing Photos'), ('DONE', 'DONE'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], max_length=10),
        ),
    ]
