# Generated by Django 3.0.3 on 2020-02-13 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200213_0103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobInfo',
        ),
    ]
