# Generated by Django 3.0.3 on 2020-02-13 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_customerinfo_paymentinfo'),
        ('photographers', '0001_initial'),
        ('jobs', '0004_delete_jobinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('JobID', models.AutoField(primary_key=True, serialize=False)),
                ('JobStatus', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('PROCESSING', 'Processing Photos'), ('COMPLETED', 'Completed')], max_length=10)),
                ('JobStartDate', models.DateField()),
                ('JobEndDate', models.DateField()),
                ('JobCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerJob', to='customers.CustomerInfo')),
                ('JobPhotographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographers.PhotographerInfo')),
            ],
        ),
    ]
