# Generated by Django 3.0.3 on 2020-02-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographerinfo',
            old_name='PhotographerEmail',
            new_name='ClientEmail',
        ),
        migrations.RenameField(
            model_name='photographerinfo',
            old_name='PhotographerFName',
            new_name='ClientFName',
        ),
        migrations.RenameField(
            model_name='photographerinfo',
            old_name='PhotographerID',
            new_name='ClientID',
        ),
        migrations.RenameField(
            model_name='photographerinfo',
            old_name='PhotographerLName',
            new_name='ClientLName',
        ),
        migrations.RenameField(
            model_name='photographerinfo',
            old_name='PhotographerPassword',
            new_name='ClientPassword',
        ),
        migrations.RenameField(
            model_name='photographerinfo',
            old_name='PhotographerSSN',
            new_name='ClientSSN',
        ),
        migrations.AddField(
            model_name='photographerinfo',
            name='ClientType',
            field=models.CharField(choices=[('PHOTOGRAPHER', 'Photographer'), ('CUSTOMER', 'Customer')], default='Customer', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographerinfo',
            name='ClientUserName',
            field=models.CharField(default='qw', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
