# Generated by Django 3.0.3 on 2020-03-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photographers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.CustomUserProfile')),
                ('photographer_price', models.FloatField(blank=True, null=True)),
                ('photographer_last_online_time', models.DateTimeField(blank=True, null=True)),
                ('photographer_avail_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographer_avail_time', to='photographers.AvailTime')),
                ('photographer_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographer_equipment', to='photographers.Equipment')),
                ('photographer_photos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographer_photos', to='photographers.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('StyleName', models.CharField(choices=[('GRADUATION', 'Graduation'), ('LANDSCAPE', 'Landscape'), ('PORTRAIT', 'Portrait'), ('PRODUCT', 'Product'), ('FASHION', 'Fashion'), ('EVENT', 'Event'), ('WEDDING', 'Wedding'), ('NONE', 'None')], max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StylePhotographerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographers.Photographer')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographers.Style')),
            ],
        ),
        migrations.AddField(
            model_name='photographer',
            name='photographer_style',
            field=models.ManyToManyField(through='photographers.StylePhotographerGroup', to='photographers.Style'),
        ),
    ]
