# Generated by Django 3.0.3 on 2020-02-24 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photographers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('StyleID', models.AutoField(primary_key=True, serialize=False)),
                ('StyleName', models.CharField(choices=[('GRADUATION', 'Graduation'), ('LANDSCAPE', 'Landscape'), ('PORTRAIT', 'Portrait'), ('PRODUCT', 'Product'), ('FASHION', 'Fashion'), ('EVENT', 'Event'), ('WEDDING', 'Wedding')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('PhotographerContact', models.CharField(max_length=100)),
                ('PhotographerPrice', models.FloatField()),
                ('PhotographerLastOnlineTime', models.DateTimeField()),
                ('PhotographerPaymentInfo', models.TextField()),
                ('PhotographerAvailTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_avail_time', to='photographers.AvailTime')),
                ('PhotographerEquipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_equipment', to='photographers.Equipment')),
                ('PhotographerPhotos', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographer_photos', to='photographers.Photo')),
                ('PhotographerStyle', models.ManyToManyField(to='photographers.Style')),
            ],
        ),
    ]
