# Generated by Django 2.2.10 on 2020-03-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_photographer_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='photographer_avail_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photographers.AvailTime'),
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='photographer_equipment',
        ),
        migrations.AddField(
            model_name='photographer',
            name='photographer_equipment',
            field=models.ManyToManyField(blank=True, null=True, related_name='photographer_equipment', to='photographers.Equipment'),
        ),
    ]
