# Generated by Django 3.0.4 on 2020-03-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_photographer_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='photographer_style',
            field=models.ManyToManyField(blank=True, null=True, related_name='styles', to='photographers.Style'),
        ),
    ]
