# Generated by Django 3.0.3 on 2020-02-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_photographer_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='EquipmentID',
        ),
        migrations.RemoveField(
            model_name='style',
            name='StyleID',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='EquipmentName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='StyleName',
            field=models.CharField(choices=[('GRADUATION', 'Graduation'), ('LANDSCAPE', 'Landscape'), ('PORTRAIT', 'Portrait'), ('PRODUCT', 'Product'), ('FASHION', 'Fashion'), ('EVENT', 'Event'), ('WEDDING', 'Wedding')], max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
