# Generated by Django 2.2.10 on 2020-03-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0003_auto_20200311_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='photographer_avail_time',
        ),
        migrations.AddField(
            model_name='photographer',
            name='photographer_avail_time',
            field=models.ManyToManyField(blank=True, null=True, to='photographers.AvailTime'),
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='photographer_photos',
        ),
        migrations.AddField(
            model_name='photographer',
            name='photographer_photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='photographer_photos', to='photographers.Photo'),
        ),
    ]
