# Generated by Django 3.0.3 on 2020-02-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0004_auto_20200219_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StyleName', models.CharField(choices=[('GRADUATION', 'Graduation'), ('LANDSCAPE', 'Landscape'), ('PORTRAIT', 'Portrait'), ('PRODUCT', 'Product'), ('FASHION', 'Fashion'), ('EVENT', 'Event'), ('WEDDING', 'Wedding')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='availtime',
            name='AvailDate',
            field=models.CharField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='PhotographerPhotos',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographer_photos', to='photographers.Photo'),
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='PhotographerStyle',
        ),
        migrations.AddField(
            model_name='photographer',
            name='PhotographerStyle',
            field=models.ManyToManyField(to='photographers.Style'),
        ),
    ]
