# Generated by Django 3.0.3 on 2020-02-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0005_auto_20200219_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availtime',
            name='AvailDate',
            field=models.CharField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=20),
        ),
    ]
