# Generated by Django 3.0.4 on 2020-03-22 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('noti_id', models.AutoField(primary_key=True, serialize=False)),
                ('noti_field', models.CharField(choices=[('PAYMENT', 'Payment'), ('JOB', 'Job')], max_length=10)),
                ('noti_action', models.CharField(max_length=100)),
                ('noti_status', models.CharField(choices=[('PENDING', 'Pending'), ('DECLINED', 'Declined'), ('MATCHED', 'Matched'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('PROCESSING', 'Processing Photos'), ('DONE', 'Done'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], max_length=10)),
                ('noti_description', models.TextField(blank=True, max_length=250, null=True)),
                ('noti_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
