# Generated by Django 3.0.4 on 2020-03-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('CREATE', 'Create'), ('DELETE', 'Delete'), ('UPDATE', 'Update')], max_length=20)),
            ],
        ),
    ]
